[package]
name = "tg-cuckoo-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
axum = "0.6.20"
clap = { version = "4.3.21", features = ["derive", "env"] }
serde = { version = "1.0.183", features = ["derive"] }
thiserror = "1.0.44"
tokio = { version = "1.30.0", features = ["macros", "rt-multi-thread"] }
