[package]
name = "tgbotool-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.4.1"
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = { version = "2.0.29", features = ["extra-traits"] }

[lib]
proc-macro = true
